import FrKernels.Edit
import FrKernels.Position
import FrKernels.History
import FrKernels.Patch
import FrKernels.Project
import FrKernels.Source
import FrKernels.Author
import FrKernels.Digest
import FrKernels.Workspace
import FrKernels.Git
